sudo: false
language: cpp
os: osx 
compiler:
  - clang
install:
  - brew install llvm ninja
script:
  - export MOJITO_CXX=`brew --prefix llvm`/bin/clang++
  - export MOJITO_CC=`brew --prefix llvm`/bin/clang
  - mkdir generator/build
  - pushd generator/build
  - cmake .. -G "Ninja" -DLLVM_DIR="/usr/local/Cellar/llvm/7.0.1/lib/cmake/llvm"
  - ninja
  - popd
  - pushd demo
  - cmake -G "Ninja" .
  - ninja
  - ./demo
  - popd
  - pushd tests
  - cmake -G "Ninja" .
  - ninja
  - ./tests
  - popd
